apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/ochan10/pro690-finals'
    path: dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  project: default
